# NumPy

## Load NumPy 


In [231]:
import numpy as np


## The Basics


In [232]:
a = np.array([1,2,3], dtype='int32')
a

array([1, 2, 3], dtype=int32)

In [233]:
# Get Dimension
a.ndim

1

In [234]:
# Get Type
a.dtype

dtype('int32')

In [235]:
# Get Size
a.itemsize

4

In [236]:
# Get total size
a.nbytes

12

In [237]:
# Get number of elements
a.size

3

In [238]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [239]:
# Get Shape
b.shape

(2, 3)



## Accessing and Changing specific elements, rows, columns, etc

In [240]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [241]:
# Get a specific element [r, c]
a[1, 5]

13

In [242]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [243]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [244]:
# Getting a specifiv section of array [startindex:endindex:stepsize]l
a[0, 1:-1:2]

array([2, 4, 6])

In [245]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [246]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3-dimensional example

In [247]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [248]:
# Get specific element (work outside in)
b[0,1,1]

4

In [249]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]



## Initializing Different Types of Arrays


In [250]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [251]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [252]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [253]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [254]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.91743234, 0.86837821],
       [0.79768017, 0.8454744 ],
       [0.27458503, 0.543373  ],
       [0.5277215 , 0.67752271]])

In [255]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 7,  4,  0],
       [ 0, -2,  6],
       [ 2, -2, -1]])

In [256]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [257]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [258]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [259]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]



## Mathematics


In [260]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [261]:
a + 2

array([3, 4, 5, 6])

In [262]:
a - 2

array([-1,  0,  1,  2])

In [263]:
a * 2

array([2, 4, 6, 8])

In [264]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [265]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [266]:
a ** 2

array([ 1,  4,  9, 16])

In [267]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### More: https://docs.scipy.org/doc/numpy/reference/routines.math.html


### Linear Algebra


In [268]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [269]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

Reference docs: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse

Etc...

### Statistics

In [270]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [271]:
np.min(stats)

1

In [272]:
np.max(stats, axis=1)

array([3, 6])

In [273]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [274]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [275]:
after = before.reshape((1,8))
print(after)

[[1 2 3 4 5 6 7 8]]


In [276]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [277]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [278]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [279]:
# Indexing with a list
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[0,1,8]]

array([1, 2, 9])

##### Boolean Masking and Advanced Indexing

In [280]:
# Find all values greater than 50, but less than 100 and returns array of booleans
(filedata > 50) & (filedata < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])


## Indexing specific parts of data


In [281]:
a = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30]])

In [282]:
# a box
print(a[2:4, 0:2])

[[11 12]
 [16 17]]


In [283]:
# diagonally
print(a[[0,1,2,3],[1,2,3,4]])

[ 2  8 14 20]


In [284]:
# Diffrent sections
print(a[[0,4,5], 3:])

[[ 4  5]
 [24 25]
 [29 30]]
